project:
  type: website
  output-dir: docs

website:
  title: "Keep moving"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_trgc1_trgc2.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



